apiVersion: v1
kind: Service
metadata:
  name: poc-node1-service
spec:
  type: NodePort
  selector:
    app: poc-node1
  ports:
    - protocol: TCP
      port: 32000
      targetPort: 32000
      nodePort: 32000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: poc-node1
spec:
  selector:
    matchLabels:
      app: poc-node1
  template:
    metadata:
      labels:
        app: poc-node1
    spec:
      containers:
      - name: poc-node1
        image: ghcr.io/dominickbrasileiro/poc-node:latest
        ports:
        - containerPort: 32000
          name: poc-node1
        volumeMounts:
        - name: data
          mountPath: /app/node/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi